import './src/styles/global.css';
import './src/components/hero.js';
import './src/components/about.js';
import './src/components/benefits.js';
import './src/components/contact.js';
import './src/components/feedback.js';
import './src/components/footer.js';
import './src/components/portfolio.js';
import './src/components/services.js';